# Generated by Django 2.2.7 on 2019-11-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.IntegerField(verbose_name='Starting Age Range')),
                ('end_range', models.IntegerField(verbose_name='Ending Age Range')),
            ],
            options={
                'unique_together': {('start_range', 'end_range')},
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='Gender')),
                ('rf_id', models.CharField(max_length=50, unique=True, verbose_name='RF ID')),
                ('ear_tag', models.CharField(max_length=50, unique=True, verbose_name='Ear ID')),
                ('birth_date', models.CharField(max_length=250, verbose_name='Birth Date')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StandardWeightCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_weight', models.FloatField(verbose_name='Starting Weight in KGs')),
                ('to_weight', models.FloatField(verbose_name='Ending Weight in KGs')),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.AgeRange')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date Time')),
                ('weight', models.FloatField(verbose_name='Weight in KGs')),
                ('heart_girth', models.FloatField(verbose_name='Heart Girth in meters')),
                ('diagonal_len', models.FloatField(verbose_name='Diagonal Length in meters')),
                ('image', models.URLField(verbose_name='Image')),
                ('depth_img', models.URLField(verbose_name='Depth Image')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Cattle')),
            ],
        ),
        migrations.AddField(
            model_name='cattle',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Status'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Alert Message')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Cattle')),
            ],
        ),
    ]
