# Generated by Django 2.2.7 on 2019-11-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='birth_date',
            field=models.DateField(verbose_name='Birth Date'),
        ),
    ]
