# Generated by Django 3.0 on 2019-12-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191121_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='status',
        ),
        migrations.AddField(
            model_name='alert',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Time'),
        ),
        migrations.CreateModel(
            name='CattleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date Time')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Cattle')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Status')),
            ],
        ),
    ]
