# Generated by Django 3.0 on 2020-01-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191217_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='dailyweight',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_weights', to='dashboard.Cattle'),
        ),
    ]
