# Generated by Django 3.0 on 2020-01-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200104_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlestatus',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_objects', to='dashboard.Cattle'),
        ),
    ]
