# Generated by Django 3.0 on 2020-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200113_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweight',
            name='date_time',
            field=models.DateTimeField(verbose_name='Date Time'),
        ),
    ]
