# Generated by Django 3.0 on 2020-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200116_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweight',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time'),
        ),
    ]
