# Generated by Django 3.0 on 2020-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200116_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweight',
            name='depth_img',
            field=models.URLField(blank=True, verbose_name='Depth Image'),
        ),
        migrations.AlterField(
            model_name='dailyweight',
            name='diagonal_len',
            field=models.FloatField(blank=True, verbose_name='Diagonal Length in meters'),
        ),
        migrations.AlterField(
            model_name='dailyweight',
            name='heart_girth',
            field=models.FloatField(blank=True, verbose_name='Heart Girth in meters'),
        ),
        migrations.AlterField(
            model_name='dailyweight',
            name='image',
            field=models.URLField(blank=True, verbose_name='Image'),
        ),
    ]
